### ISSUE TITLE
Upgrading to Portable version

### ISSUE THREAD

**Issue by BobPannell** [didierterrien/Power-BI-Sidetools#32] opened 2021-11-17 16:37 UTC
I have just upgraded to portable version.
Excel files created using Export to Excel now save to a different sub-folder.  
Is it possible for PowerBI Sidetools to retrieve Excel files created in previous version of Sidetools (those saved to C:\Users\your username\Documents\ ...) and so update their contents, or do I need to re-create from first principles?
Thanks
Bob

**Comment by didierterrien** [comment] 2021-11-17 19:14
Hello Bob,
You may modify folders in Sidetools settings in order to have the same paths than before. This is the easiest solution.

Otherwise, you can move your Excel file to new folders. If you do so, in each Excel file, you need to change the connection. Follow these steps and save your Excel file :

![image](https://user-images.githubusercontent.com/37301981/142266858-73cec92a-e6cd-419e-bd47-5292b71d043a.png)

Let me know if it woks so I can close the issue.

**Comment by BobPannell** [comment] 2021-11-18 10:03
Hi Didier

 

Thank you for the quick and helpful reply.

 

Your first and easiest solution works.  The earlier naming convention does mean that my Exports folder is now “5. = EXPORTS ====etc” and my Translations folder is “5.= TRANSLATIONS ===etc”, but hopefully that is not an issue.

 

I tried migrating one Excel file using your second approach, but unfortunately I did not seem able to make the change in Connection file a permanent one.  This meant that when reopening my pbix file and attempting to refresh Excel file, an Analysis Services wizard window popped up asking me for User ID and password.

 

Thanks again for your help.  Fantastic!

 

Bob

**Comment by didierterrien** [comment] 2021-11-18 11:37
Hello Bob,
I cannot reproduce this error. Please check :
- you selected 'Export to Excel.odc' and not 'Export table to Excel.odc'
- the 'Export to Excel.odc' file you select has a recent date & time
- you replied yes in the message box at the end 

After you modified the connection, you can go back to the connexion settings and check if it's correct. You may send a screenshot of the connexion settings here.

 'Export to Excel.odc' file is created by Sidetools when you click in 'Export to Excel' menu. It's location is 'Projects folder' setting + Your Pbix file name + 'Exports folder' setting. Your Excel export files must be located in the same directory
Hope it helps

**Comment by didierterrien** [comment] 2021-11-18 14:52
I got the same issue with another Excel file today. 
I created a new connexion using the  'Export to Excel.odc' file and I checked the 'Refresh data when the file is opened' checkbox in the first tab. Then, for each pivot table, I changed the data source to the new connexion :

![image](https://user-images.githubusercontent.com/37301981/142437373-d95da06d-526c-4d98-90c9-b83013fb1b62.png)

Finally, I deleted the old connexion

**Comment by didierterrien** [comment] 2021-11-25 09:46
I'm closing the issue. Feel free to reopen if the problem is not solved

**Closed by didierterrien** 2021-11-25 09:46 UTC
Labels: documentation
