### ISSUE TITLE
Not responding, results in crash for v1.2.7 (test)

### ISSUE THREAD

**Issue by hlynurarni** [didierterrien/Power-BI-Sidetools#31] opened 2021-09-23 09:02 UTC
I tried out the latest test version 1.2.7 on 21. September

I got a none responding when I launched it ( I had another PBI desktop instance running that I didn't notice, before I installed the new version). After giving not responding some time I  tried to exit the Power Bi desktop and when the application finally shut down  --> all my apps and local files had vanished...

Really strange behaviour and I can't 100% confirm that it was Sidetools fault, but it looks like it. I don't have running computer at the moment because of this and just wanted to give you an update and maybe get your thoughts on why this could happen ?

**Comment by didierterrien** [comment] 2021-09-23 10:03
Thank you for reporting !
If you launch Sidetools while more than one report is open, a window asks you which report to connect :

![image](https://user-images.githubusercontent.com/37301981/134488107-474040ae-eb48-4afe-a738-4197fe248385.png)

This window must be closed before Sidetools window will open.

What do you mean by "all my apps and local files had vanished" ? 

Please send the log file

**Comment by hlynurarni** [comment] 2021-09-23 10:42
okay, I used clicked the process button on the report that I wanted to work on and everything went sideways.

In the process of having not responding issue I closed everything on my computer and restarted, thats where I noticed the big problem. 

All my local files got deleted somehow, 

Downloads folder empty, folders under programs files deleted so I cant launch most of my apps and local setting on my folder structure in "folder explorer", just to name the most obvious ones I have seen. 

System restore is not successful (as expected since files they are all gone and only saved locally before crash)

I cant give any more detail to the issue than that, but I thought it would be important to raise it if Sidetools was the thing that caused it (I don't see any other obvious reasons for it")

No log files created during this process...

**Comment by didierterrien** [comment] 2021-09-23 11:01
First of all I feel really sorry for what happened. I will try to figure out if Sidetools can be responsible of such a disaster. At the moment, I'm quite sure Sidetools cannot delete program files folders or any other vital folders. I use Sidetools everyday and I never noticed a system folder was deleted. Anyway, I will check it intensively and will let you know.

**Comment by hlynurarni** [comment] 2021-09-23 11:57
Thanks for that, only small portion of valuable files got lost. 

It is not unlikely that this a windows operating fail, I am run on Mac for own use so I am not too familiar with what can really crash in the windows operating system.

Thanks for the quick replies and good work ! (not blaming you for the crash just so that is clear)

**Comment by didierterrien** [comment] 2021-09-24 09:45
I need to be sure Sidetools cannot harm users system so I continue to investigate.
Did you see the update window and if yes, did you click on 'Process' button before it crashed ?
Can you give me more precise location of the files which were lost ?
Did you modify folders in Sidetools settings ? If yes, can you send a screenshot ?

**Comment by didierterrien** [comment] 2021-09-27 14:09
After a deep analysis, I confirm Sidetools V1.2.7 doesn't delete any system folder.
I close the issue but feel free to reopen it if necessary

**Closed** 2021-09-27 14:10 UTC

**Comment by hlynurarni** [comment] 2021-09-28 12:00
Thank you for the update I will continue to experiment with 1.2.7 without worrying about system crash. 

I did notice one thing when I launched 1.2.7 that my previous settings had been set to default...didn't think too much about it and just checked the boxes that I wanted to use. 

I did not get the update window when I installed (it just installed a new version with the old one being there too)

Did not modify any Sidetools folder but my settings were off like I mentioned above.

The location of lost files:
- mostly in program files (apps and .exe files)
- Download folder cleared
- All app data lost (chrome tabs and such..) that means the Appdata hidden folder was altered on too.

My observation of how it happened:
- Cortana caused the crash (accidentally clicked it and closed it right away in the midst of all this) (got error message after restart, will update what it was when I have access tomorrow)
- I had 2 versions of sidetools isntalled, had powerbi open with another version of sidetools running (by mistake), ignored the phishy thing going on with settings, clicked the process button and the system (windows) had some crash because of that all

This led to a screen flickering and all icons going white (windows did not recognise them anymore). Not able to run any apps do to this... 

I did restart the computer with everything being the same (white icons and lost files). I get a error message, on which google led me to Cortana being corrupt, I restore Cortana, restart computer message is gone but everything is still lost. 

System restore did not work (issues with restoring/deleting onedrive folders, unlinking let to restoring it only being an issue). No windows.old files or folders on the computer and no file names found that I used to have. So I gave up on System restore, cant restore something that is no longer on the local disc and was only saved on local disc.

Thanks for looking into this, I agree that the case should be closed after your thorough examination.

**Comment by hlynurarni** [comment] 2021-09-28 12:37
Could you please fix the "contact" feature on your website it doesn't work.

<img width="865" alt="Screenshot 2021-09-28 at 14 36 24" src="https://user-images.githubusercontent.com/10733420/135088138-efc8a032-3f3b-4427-9ecd-e37eb9925be9.png">

**Comment by didierterrien** [comment] 2021-09-29 09:30
Thank you for reporting !

I cannot reproduce the error with the contact form. That's bad for my website. Don't have time for this now cause I prepare a major feature for next weeks

![image](https://user-images.githubusercontent.com/37301981/135241863-c8b311db-4ca3-4897-a9da-4a1acab244dd.png)
